apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: workout-tracker
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres