apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: workout-tracker
type: Opaque
stringData:
  POSTGRES_DB: workoutdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres